/* Generated By:JavaCC: Do not edit this line. EG1Constants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface EG1Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUM = 5;
  /** RegularExpression Id. */
  int ID = 6;
  /** RegularExpression Id. */
  int LETTER = 7;
  /** RegularExpression Id. */
  int DIGIT = 8;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<NUM>",
    "<ID>",
    "<LETTER>",
    "<DIGIT>",
    "\"<\"",
    "\"|\"",
    "\">\"",
    "\"->#\"",
    "\"(\"",
    "\"#\"",
    "\",\"",
    "\")>\"",
    "\"circuit \"",
    "\";\"",
  };

}
